"""
Step 2: NLP Analysis & Document Creation using Gemini 1.5 Pro
Output: Professional PDF
"""

import os
import sys
import markdown
import google.generativeai as genai
from xhtml2pdf import pisa

# API Key
os.environ["GEMINI_API_KEY"] = "YOUR_GEMINI_API_KEY_HERE"

def setup_gemini():
    api_key = os.environ.get("GEMINI_API_KEY")
    genai.configure(api_key=api_key)
    return genai.GenerativeModel(model_name="gemini-1.5-flash-8b")

def convert_html_to_pdf(source_html, output_filename):
    result_file = open(output_filename, "w+b")
    pisa_status = pisa.CreatePDF(
            source_html,
            dest=result_file)
    result_file.close()
    return pisa_status.err

def main():
    input_file = "transcript.txt"
    if len(sys.argv) > 1:
        input_file = sys.argv[1]

    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found. Run transcribe.py first!")
        sys.exit(1)

    print(f"Reading {input_file}...")
    with open(input_file, "r", encoding="utf-8") as f:
        transcript_text = f.read()

    model = setup_gemini()
    
    print("\nAnalyzing text using NLP...")
    
    prompt = f"""
    You are an expert executive secretary.
    Here is the raw transcript of a meeting:
    
    <transcript>
    {transcript_text}
    </transcript>
    
    Please generate a professional 'Minutes of Meeting' document. 
    Use succinct business language.
    The response must be in standard Markdown.
    
    Structure:
    # Minutes of Meeting
    **Date:** [Current Date]
    
    ## 1. Executive Summary
    (Brief summary of the meeting).
    
    ## 2. Attendees
    (List inferred attendees).
    
    ## 3. Key Discussion Points
    *   Point 1
    *   Point 2
    
    ## 4. Decisions Made
    *   Decision 1
    *   Decision 2
    
    ## 5. Action Items
    (Use a markdown table for Action Items: Task | Owner | Deadline)
    """
    
    response = None
    for attempt in range(3):
        try:
            response = model.generate_content(prompt)
            break
        except Exception as e:
             if "429" in str(e) or "ResourceExhausted" in str(e):
                print(f"\nRate limit hit (NLP). Retrying in 60 seconds... (Attempt {attempt+1}/3)")
                import time
                time.sleep(60)
             else:
                raise e
    
    if not response:
        print("Error: Could not generate minutes after 3 attempts due to Rate Limiting.")
        sys.exit(1)

    md_text = response.text
    
    # Save generic markdown just in case
    with open("minutes_temp.md", "w", encoding="utf-8") as f:
        f.write(md_text)

    # Convert to PDF
    print("Formatting PDF...")
    
    # 1. Convert Markdown to HTML
    html_body = markdown.markdown(md_text, extensions=['tables'])
    
    # 2. Add Professional CSS/HTML Template
    full_html = f"""
    <html>
    <head>
    <style>
        body {{
            font-family: Helvetica, Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            font-size: 24pt;
            text-align: center;
            margin-bottom: 30px;
        }}
        h2 {{
            color: #2980b9;
            font-size: 16pt;
            margin-top: 25px;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }}
        p {{
            margin-bottom: 10px;
            text-align: justify;
        }}
        ul {{
            margin-bottom: 10px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            margin-bottom: 15px;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }}
        th {{
            background-color: #f2f2f2;
            color: #333;
            font-weight: bold;
        }}
        .footer {{
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10pt;
            color: #777;
        }}
    </style>
    </head>
    <body>
        {html_body}
        <div class="footer">Generated by AI Secretary</div>
    </body>
    </html>
    """
    
    output_pdf = "Minutes_of_Meeting.pdf"
    if convert_html_to_pdf(full_html, output_pdf):
        print("Error generating PDF.")
    else:
        print(f"\n[Success] Professional PDF saved to {output_pdf}")

if __name__ == "__main__":
    main()
